name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  node:
    name: Node workflow
    uses : ./.github/workflows/node.yml

  docker:
    name: Docker Workflow
    uses: ./.github/workflows/docker.yml